 {{-- <script src="https://home.kartra.com/js/build/front/pages/skeleton-immediate.js"></script>
    <script src="https://home.kartra.com/js/build/front/pages/skeleton-below.js" async defer></script>
    <script src="http://app.kartra.com/resources/js/analytics/R8g82rqP" async defer></script>
    <script src="http://app.kartra.com/resources/js/page_check?page_id=wUeM7yHb4QrK" async defer></script>
    <script>
        if (typeof window['jQuery'] !== 'undefined') {
            window.jsVars = {
                "vendor_time_format": "12h",
                "page_title": "Kartra - Your Online Business Made Easy",
                "page_description": "Your Online Business Made Easy - Create, market & launch online without hiring a team of copywriters, web developers, designers or system integrators!",
                "page_keywords": "All in one online business, email autoresponder, sales checkout, membership portal, page builder",
                "page_robots": "noindex, nofollow",
                "secure_base_url": "\/\/app.kartra.com\/",
                "global_id": "wUeM7yHb4QrK"
            };
            window.global_id = 'wUeM7yHb4QrK';
            window.secure_base_url = 'http://app.kartra.com/';

            window.parent.postMessage({
                title: window.jsVars.page_title,
                description: window.jsVars.page_description,
                keywords: window.jsVars.page_keywords,
                robots: window.jsVars.page_robots,
                domain: 'app.kartra.com'
            }, '*');

            // trigger the analytics on modal shown
            jQuery(window).on('shown.bs.modal', function (e) {
                if (typeof e.target !== 'undefined') {
                    var modalClass = e.target.className;
                    if (modalClass !== '') {
                        var modalElements = document.getElementsByClassName(modalClass);
                        if (typeof modalElements[0] !== 'undefined') {
                            var event = new Event('kartra_show_hidden_asset');
                            modalElements[0].dispatchEvent(event);
                        }
                    }
                }
            });

            if (typeof Porthole !== 'undefined') {
                //domainn is a separate variable to domain
                windowProxy = new Porthole.WindowProxy('//kartra.kartra.com/front/deal/proxy');
            }
        }
    </script>
    <footer>
        <div style="height:0px;width:0px;opacity:0;position:fixed">
            <img src="https://app.kartra.com/button/tc/4efa31d18a7847f18075db8e3f898652"
                style="border:0px; width:0px; height: 0px;" />
            <img src="https://app.kartra.com/button/tc/8a00cafc10964d3a087f8820b4c9fdf6"
                style="border:0px; width:0px; height: 0px;" />
            <img src="https://app.kartra.com/button/tc/2c900cadc4f1bf2d31d1edccf5462740"
                style="border:0px; width:0px; height: 0px;" />
            <img src="https://app.kartra.com/button/tc/17f52e6d61a916b7edcffdd260e8b5ba"
                style="border:0px; width:0px; height: 0px;" />
            <img src="https://app.kartra.com/button/tc/7f40a53cdce6ce0a93aa664491b5fbf0"
                style="border:0px; width:0px; height: 0px;" />
            <img src="https://app.kartra.com/button/tc/b40443461ddab9e7a0843c1969a86129"
                style="border:0px; width:0px; height: 0px;" />
            <img src="https://app.kartra.com/button/tc/330105e4752911a076a79a31d1c10047"
                style="border:0px; width:0px; height: 0px;" />
            <img src="https://app.kartra.com/button/tc/9bd1badcd456b82ddf1855db789c68ef"
                style="border:0px; width:0px; height: 0px;" />
            <!-- Hotjar Tracking Code for https://home.kartra.com/index -->

            <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
            <script type="application/ld+json">
                {
                    "@context": "http://schema.org",
                    "@type": "SoftwareApplication",
                    "name": "Kartra",
                    "image": "https://d1aettbyeyfilo.cloudfront.net/Kartra/4977206_1563315585501KArtra-LogoPNG.png",
                    "url": "https://www.kartra.com/",
                    "publisher": {
                        "@type": "Organization",
                        "name": "Genesis Digital LLC"
                    },
                    "applicationCategory": "Marketing Ecommerce",
                    "downloadUrl": "https://home.kartra.com/plans",
                    "operatingSystem": "Any",
                    "requirements": "Browser",
                    "screenshot": "https://d1aettbyeyfilo.cloudfront.net/Kartra/3438945_155080330461472.jpg"
                }
            </script>

            <script>
                (function () {
                    var s = document.createElement('script'),
                        e = !document.body ? document.querySelector('head') : document.body;
                    s.src = 'https://acsbapp.com/apps/app/assets/js/acsb.js';
                    s.async = s.defer = true;
                    s.onload = function () {
                        acsbJS.init({
                            statementLink: '',
                            feedbackLink: '',
                            footerHtml: 'Genesis Digital, LLC',
                            hideMobile: false,
                            hideTrigger: false,
                            language: 'en',
                            position: 'left',
                            leadColor: '#333333',
                            triggerColor: '#333333',
                            triggerRadius: '50%',
                            triggerPositionX: 'left',
                            triggerPositionY: 'bottom',
                            triggerIcon: 'default',
                            triggerSize: 'medium',
                            triggerOffsetX: 20,
                            triggerOffsetY: 20,
                            mobile: {
                                triggerSize: 'small',
                                triggerPositionX: 'left',
                                triggerPositionY: 'center',
                                triggerOffsetX: 0,
                                triggerOffsetY: 0,
                                triggerRadius: '0'
                            }
                        });
                    };
                    e.appendChild(s);
                }());
            </script>
        </div>
    </footer>
    <!-- GDPR cookie BANNER -->
    <div class="gdpr_cookie_banner js_gdpr_cookie_banner" style="display: none;">
        <button type="button" class="gdpr-uncollapse-button js_show_gdpr_banner">
            Cookies
        </button>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="d-grid grid-gdpr-banner grid-col-gap-60px">
                        <div>
                            <div class="js_gdrp_cookie_banner_text gdpr-text">
                                We use cookies to improve our service, track analytics, remember preferences, etc. By
                                using our site, you consent to these cookies.
                            </div>
                            <div class="gdpr_link_wrapper">
                                <a href="#" target="_blank" class="js_gdpr_button">Privacy policy</a>
                                <span></span>
                                <a href="#" target="_blank" class="">Cookie policy</a>
                            </div>
                        </div>
                        <div class="gdpr_button_block">
                            <div class="gdpr_toggler">
                                <label class="toggler_label selected">Accept all cookies</label>
                                <div class="switcher">
                                    <input type="checkbox" name="gdpr_cookies" id="gdpr_cookies"
                                        class="cmn-toggle js_accepted_cookies" value="2">
                                    <label for="gdpr_cookies"></label>
                                </div>
                                <label class="toggler_label ">Only essential cookies</label>
                            </div>
                            <button class="gdpr_close js_gdpr_close" type="button" data-type="kartra_page"
                                data-type-id="960" data-type-owner="R8g82rqP">SAVE</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--// GDPR cookie BANNER -->

    <script src="http://app.kartra.com/resources/js/kartra_embed_wild_card?type=kartra_page&amp;owner=R8g82rqP">
    </script>
    <script defer
        src="https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194"
        integrity="sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw=="
        data-cf-beacon='{"rayId":"6e7f2a171a3096cc","token":"fd31622ef90d4da1b9d6f9db2c97b1bf","version":"2021.12.0","si":100}'
        crossorigin="anonymous"></script> --}}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="{{asset('assets/js/main.js')}}"></script>
